**1) Generate an array of zeroes using inbuilt numpy function.**

In [7]:
import numpy as np

array_x = np.zeros([5,5])
array_x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**2) Run the given code and find the dot product of both arrays.**

In [9]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[4 9 7 4]
 [8 9 4 6]
 [3 8 3 6]]
[[9 5 4]
 [5 7 5]
 [3 2 6]
 [4 3 5]]


In [10]:
a.dot(b)

array([[118, 109, 123],
       [153, 129, 131],
       [100,  95, 100]])

**3)Read the csv file provided using pandas and display the first 5 entries**

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [16]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data.csv')
data.head(5)

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

**4)Describe the data with all features.**

In [18]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   OBJECTID       25 non-null     int64  
 1   UNIT_NAME      25 non-null     object 
 2   DESCRIPTION    25 non-null     object 
 3   ACRES          25 non-null     float64
 4   SHAPE.AREA     25 non-null     float64
 5   SHAPE.LEN      25 non-null     float64
 6   (0, OBJECTID)  25 non-null     float64
 7   0              25 non-null     float64
dtypes: float64(5), int64(1), object(2)
memory usage: 1.7+ KB


**5) Find the total count of missing values for each feature.**

In [21]:
data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

**6) Display all the unique values from the 'DESCRIPTION’ column.**

In [22]:
data['DESCRIPTION'].unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

**7)Create a grouped table using  'DESCRIPTION' as the grouping columns with the means of all the other columns.**

In [23]:
data.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

**8) Generate a random sample of 10 rows from the data.**

In [27]:
random_sample = data.sample(10)
random_sample

OBJECTID                                   UNIT_NAME  \
2         23             Fort Abraham Lincoln State Park   
13        36       Crow Flies High State Recreation Area   
19        40  Head of the Mountain State Nature Preserve   
11        32                      Sully Creek State Park   
24        42         Pelican Point State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
16        37                  Elkhorn State Natural Area   
10        31                  Little Missouri State Park   
12        35        Butte St. Paul State Recreation Area   
0         21                   Fort Stevenson State Park   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  
2              State Park   836.47    0.000399   0.119868  
13  State Recreation Area   247.11    0.000120   0.050518  
19  State Nature Preserve    72.30    0.000034   0.033885  
11             State Park    63.03    0.000030   0.024016  
24  State Recreation Area    25.22    0.000013   0.026357  
22  State Recreation Area   695.04    0.000345   0.086487  
16     State Natural Area   264.84    0.000127   0.067082  
10             State Park  6492.93    0.003136   0.313756  
12  State Recreation Area    51.23    0.000025   0.022095  
0              State Park   586.48    0.000284   0.135641

**9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.**

In [37]:
array_small = list(np.random.rand(10))
random_sample['New_Feature']= list(array_small)
random_sample

OBJECTID                                   UNIT_NAME  \
2         23             Fort Abraham Lincoln State Park   
13        36       Crow Flies High State Recreation Area   
19        40  Head of the Mountain State Nature Preserve   
11        32                      Sully Creek State Park   
24        42         Pelican Point State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
16        37                  Elkhorn State Natural Area   
10        31                  Little Missouri State Park   
12        35        Butte St. Paul State Recreation Area   
0         21                   Fort Stevenson State Park   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New_Feature  
2              State Park   836.47    0.000399   0.119868     0.313054  
13  State Recreation Area   247.11    0.000120   0.050518     0.155913  
19  State Nature Preserve    72.30    0.000034   0.033885     0.380888  
11             State Park    63.03    0.000030   0.024016     0.255660  
24  State Recreation Area    25.22    0.000013   0.026357     0.300485  
22  State Recreation Area   695.04    0.000345   0.086487     0.003347  
16     State Natural Area   264.84    0.000127   0.067082     0.418653  
10             State Park  6492.93    0.003136   0.313756     0.786633  
12  State Recreation Area    51.23    0.000025   0.022095     0.144340  
0              State Park   586.48    0.000284   0.135641     0.032373

**10) Replace zero value of column 'OBJECTID' with mean value permanently.**

In [46]:
data.iloc[0] = data['OBJECTID'].mean()
data

OBJECTID                                   UNIT_NAME  \
0      33.48                                       33.48   
1      22.00                      Beaver Lake State Park   
2      23.00             Fort Abraham Lincoln State Park   
3      24.00                      Fort Ransom State Park   
4      25.00                   Grahams Island State Park   
5      26.00                        Icelandic State Park   
6      27.00                   Lake Metigoshe State Park   
7      28.00                  Lewis and Clark State Park   
8      29.00         Lewis and Clark Interpretive Center   
9      30.00           Fort Mandan State Recreation Area   
10     31.00                  Little Missouri State Park   
11     32.00                      Sully Creek State Park   
12     35.00        Butte St. Paul State Recreation Area   
13     36.00       Crow Flies High State Recreation Area   
14     33.00                     Turtle River State Park   
15     34.00                   Lake Sakakawea State Park   
16     37.00                  Elkhorn State Natural Area   
17     38.00         Fahlgren Park State Recreation Area   
18     39.00             Gunlogson State Nature Preserve   
19     40.00  Head of the Mountain State Nature Preserve   
20     41.00           Missouri River State Natural Area   
21     43.00         Pembina Gorge State Recreation Area   
22     44.00       Turtle Mountain State Recreation Area   
23     45.00                      Cross Ranch State Park   
24     42.00         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  (0, OBJECTID)  \
0                   33.48    33.48   33.480000  33.480000          33.48   
1              State Park   273.16    0.000129   0.080067          33.00   
2              State Park   836.47    0.000399   0.119868          33.00   
3              State Park   933.78    0.000444   0.128733          33.00   
4              State Park   959.33    0.000469   0.125546          33.00   
5              State Park   930.30    0.000461   0.166712          33.00   
6              State Park  1508.53    0.000751   0.212196          33.00   
7              State Park   524.81    0.000256   0.130420          33.00   
8     Interpretive Center    14.71    0.000007   0.016774          33.00   
9   State Recreation Area    11.40    0.000005   0.009396          33.00   
10             State Park  6492.93    0.003136   0.313756          33.00   
11             State Park    63.03    0.000030   0.024016          33.00   
12  State Recreation Area    51.23    0.000025   0.022095          33.00   
13  State Recreation Area   247.11    0.000120   0.050518          33.00   
14             State Park   775.28    0.000378   0.145220          33.00   
15             State Park   739.52    0.000357   0.191806          33.00   
16     State Natural Area   264.84    0.000127   0.067082          33.00   
17  State Recreation Area    21.56    0.000010   0.013294          33.00   
18  State Nature Preserve    95.89    0.000048   0.040465          33.00   
19  State Nature Preserve    72.30    0.000034   0.033885          33.00   
20     State Natural Area   174.39    0.000083   0.087192          33.00   
21  State Recreation Area  1236.98    0.000615   0.338800          33.00   
22  State Recreation Area   695.04    0.000345   0.086487          33.00   
23             State Park   569.07    0.000274   0.180257          33.00   
24  State Recreation Area    25.22    0.000013   0.026357          33.00   

        0  
0   33.48  
1   33.00  
2   33.00  
3   33.00  
4   33.00  
5   33.00  
6   33.00  
7   33.00  
8   33.00  
9   33.00  
10  33.00  
11  33.00  
12  33.00  
13  33.00  
14  33.00  
15  33.00  
16  33.00  
17  33.00  
18  33.00  
19  33.00  
20  33.00  
21  33.00  
22  33.00  
23  33.00  
24  33.00